### ISSUE TITLE
Prestashop Module Page error

### ISSUE THREAD

**Issue by bedanta1998** [PrestaShop/openpayprestashop#12]
Hello, this is Bedanta. I'm unable to open Module page in prestashop. When I move to that page, an error message occurs : 
[PrestaShop] Fatal error in module file :/home/shoppingbull/public_html/modules/modrefchange/modrefchange.php:
syntax error, unexpected ''.bak'' (T_CONSTANT_ENCAPSED_STRING)
Please help me solving the issue.
![image](https://cloud.githubusercontent.com/assets/26488745/24052684/60af8448-0b5c-11e7-975f-91242508ddb9.png)

**Comment by fedebalderas** [comment]
OpenpayPrestashop it's not the module that have the problem: check out the path "**modrefchange**"
